[project]
name = "stepts-tools"
version = "0.1.0"
description = "Utility scripts for validating STEP files"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.uv]
default-groups = []
